version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    command: [--auth]
    ports:
      - 27017:27017
    volumes:
      #- $HOME/Docker-Data/mongodb-data/db:/data/db
      #- $HOME/Docker-Data/mongodb-data/config:/data/configdb
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
